repoURL: 'https://github.com/dev-chulbuji/devops_k8s.git'
apps:
  - name: demo
    project: default
    namespace: default
    source:
      path: demo
      customValues: true
      values:
        - values-eks.yaml