repoURL: 'https://github.com/dev-chulbuji/devops_k8s.git'
apps:
  - name: prometheus
    project: dev
    namespace: prom
    source:
      path: prometheus
  - name: demo
    project: dev
    namespace: default
    source:
      path: demo
  - name: sample-helm-1
    project: dev
    namespace: default
    source:
      path: sample-helm-1
  - name: sample-helm-2
    project: dev
    namespace: default
    source:
      path: sample-helm-2