apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sample-helm.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: eks-iam-test-s3
    spec:
      serviceAccountName: iam-test
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: {{ .Values.image.args }}
      restartPolicy: Never