autoscaling:
  enabled: false

testFramework:
  enabled: false

service:
  enabled: true
  type: NodePort
  nodePort: 32081

grafana.ini:
  datasources:
    name: Prometheus
    type: prometheus
    url: http://prometheus-server.prom.svc.cluster.local
    access: proxy
    isDefault: true