clusterName: "elasticsearch-local"
extraEnvs:
  - name: xpack.security.enabled
    value: "false"

replicas: 1
minimumMasterNodes: 1

esJavaOpts: "-Xmx512m -Xms512m -Xlog:disable"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

service:
  enabled: true
  type: NodePort
  nodePort: 30100