clusterName: "elasticsearch-local"

esJavaOpts: "-Xmx512m -Xms512m -Xlog:disable"
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi

service:
  enabled: true
  type: NodePort
  nodePort: 30100