apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    cluster: local
    application: app-of-apps
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: app-of-apps
    repoURL: {{ $.Values.repoURL }}
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: cluster
          value: {{ $.Values.cluster }}
  syncPolicy:
    automated: {}
